# docker exec -it {{container_name}} /bin/bash

version: '3'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - $PWD/docker/database:/var/lib/postgresql/data
  cache:
    image: redis
    container_name: cache
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    ports:
      - 6379:6379
    volumes:
      - $PWD/docker/cache:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
