name: Test

on:
  push:
    branches: [develop, feature/*, refactor/*, bugfix/*, hotfix/*]
    paths:
      - "server/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "server/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          cd server/
          npm ci
      - name: starting tests
        run: |
          cd server/
          npm run test
